---
title: "Lab: Modeling a Dependent SI/SIS Epidemic"
author: "Day 4 | Network Modeling for Epidemics"
output:
  html_document:
    toc: no
---

## ...Continued from yesterday
1. Build a dynamic network animation by simplifying your Day 3 model down to a small size (n = 100), recalculating the network statistics, running a single simulation over a short number of time steps, and following the animation tutorial code.

#### Then: 

2. Back at the larger size network, incorporate vital dynamics for your model by adjusting the model parameterization for birth (arrival) and death (departure) rates in both the network model estimation and simulation. 
3. Simulate this over an SI or SIS disease type; now an SI model will be interesting! For an SI model, how does changing the vital dynamic rates change the epidemic dynamics?
4. Make sure to conduct post-simulation diagnostics and compare against the pre-simulation diagnostics.
5. Consider new model parameterizations for the network, including forms of differential activity or mixing by attributes.

#### Then:

6. Consider adding serosorting into your model...
7. ...or time-varying parameters...
8. ...or interventions.

9. Simulate counterfactual epidemic models varying key parameters (for 6, 7, or 8), and calculate some summary statistics comparing the two scenarios by extracting the data frame (e.g., number or proportion of infections averted in scenario 1 vs scenario 2).
