# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

remove_node_attr_cpp <- function(attr_list, posit_ids) {
    .Call(`_EpiModel_remove_node_attr_cpp`, attr_list, posit_ids)
}

discord_edgelist_cpp <- function(el, status, active, infstat, at_val) {
    .Call(`_EpiModel_discord_edgelist_cpp`, el, status, active, infstat, at_val)
}

update_cuml_edgelist_cpp <- function(cuml_head, cuml_tail, cuml_start, cur_head, cur_tail, at) {
    .Call(`_EpiModel_update_cuml_edgelist_cpp`, cuml_head, cuml_tail, cuml_start, cur_head, cur_tail, at)
}

shiftVec <- function(x, y) {
    .Call(`_EpiModel_shiftVec`, x, y)
}

delete_vertices_cpp <- function(el, vid, n) {
    .Call(`_EpiModel_delete_vertices_cpp`, el, vid, n)
}

